Enable Service mesh feature for ASM to install in GKE
GoogleCloudPlatform/gke-securing-third-party-apps-blueprint pull request #26
Opened 2022-06-10 09:38 UTC by laurentgrangeau

Fixes #25 
@ferrarimarco Can you take a look at it ?

2022-06-10 09:46 UTC, ferrarimarco requested changes
Thanks for this PR @laurentgrangeau ! A couple of small nits and we can merge. Thanks!

Update: can you also rebase this branch on the latest `main`? Thanks for testing those provider updates as well!

2022-06-10 09:46 UTC, ferrarimarco commented on terraform/variables.tf
> +  description = "Anthos Service Mesh feature. It is required to install the different ASM CRDs."
"Set to true to enable Anthos Service Mesh feature. It is required to install the ASM CRDs."

2022-06-10 09:46 UTC, ferrarimarco commented on terraform/variables.tf
> +  default = "true"
Change to set this to a boolean (`true`), not to a string as you're doing now (`"true"`).

2022-06-10 11:53 UTC, laurentgrangeau commented
Should be good now

2022-06-13 07:04 UTC, ferrarimarco requested changes
A minor formatting nit, and we're there. Thanks!

2022-06-13 07:04 UTC, ferrarimarco commented on terraform/asm.tf
> +  enable_mesh_feature = var.asm_enable_mesh_feature
Minor nit: can you please format this? You can either run [terraform fmt](https://www.terraform.io/cli/commands/fmt) or let your editor do it if configured accordingly.

If there are formatting changes in other files, please ignore it so we focus on these changes only. Thanks!

2022-06-13 08:15 UTC, laurentgrangeau commented
Hi @ferrarimarco everything has been formatted and rebased against `main`
It should be good now

2022-06-13 08:23 UTC, ferrarimarco approved these changes

2022-06-13 08:38 UTC, merged